name: WoolTrees
main: haveric.woolTrees.WoolTrees
version: 1.2
dev-url: http://dev.bukkit.org/server-mods/wool-trees/
depend: [Vault]
description: >
             Create wool trees by dyeing saplings.
commands:
    wooltrees:
        description: Adjust config values for Wool Trees
        usage:
    wt:
        description: Adjust config values for Wool Trees
        usage: