name: WoolTrees
main: haveric.woolTrees.WoolTrees
version: 1.2.1
author: haveric
dev-url: http://dev.bukkit.org/server-mods/wool-trees/
softdepend: [Vault]
description: >
             Create wool trees by dyeing saplings.
commands:
    wooltrees:
        aliases: [wt]
        description: Adjust config values for Wool Trees
        usage: